# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/apiKonami*"
  to = "https://img.yugioh-card.com/en/downloads/forms/KDE_DeckList.pdf"
  status = 200
[[redirects]]
  from = "/api*"
  to = "https://db.ygoprodeck.com/api/v7/cardinfo.php"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"